title: "Social Work Sandbox"
description: "An open-source portfolio of research, practice reflections, and clinical frameworks."
theme: jekyll-theme-cayman

# Social Preview & Interface Assets
og_image: "https://mmonfils.github.io/social-work-sandbox/assets/thumbnail.png"
favicon: "https://mmonfils.github.io/social-work-sandbox/assets/favicon.png"
